### ISSUE TITLE
C++ちゃんのアクセサリとGC

### ISSUE THREAD

**Issue by zettsu-t** [YSRKEN/Unofficial-RCG-Manual#2]
細かいことで恐縮ですが、Readme.mdの以下の点はあっていますでしょうか。

- 目次にC++ちゃんが居ません
- キャラクター概説における、C++ちゃんのアクセサリーはブローチではないでしょうか。CちゃんがC++ちゃんに変身したときに、Boost C++ Librariesのロゴをあしらった飾りが、襟元についています。

それと訂正ではなく追記ですが、C++を使う理由としては、C++がtracing GCを標準で使わないため、オブジェクトの破棄時間を予測できるようになる(いつデストラクタを呼び出すかが規定されている)、ということがあります。第3話の運動会でJavaちゃんが固まっていましたが、GCに起因する停止時間が長い(かつ予測可能かどうかという)ことと、GC自体の実行時間が長いことは別の課題です(下記参照)。

http://matsu-www.is.titech.ac.jp/~endo/gc/gc.pdf

"ガベージコレクション 自動的メモリ管理を構成する理論と実装", Richard Jones, Antony Hosking, Eliot Moss 著/前田敦司, 鵜川始陽, 小宮常康 訳, 2016/03, 翔泳社

**Comment by YSRKEN** [comment]
@zettsu-t 返答が遅れてしまい申し訳ありません。
・目次にC++ちゃんの項目を追加しました
・髪に付いている髪飾りは今まで「髪留め」と表記していましたが、前者の方がより適切だと思ったので修正しました
・Boostロゴについても追記しました
・C++のGCについてですが、それはReadme.mdではなく個別記事についての追記でしょうか？

**Comment by zettsu-t** [comment]
下記について、変更されていることを確認しました。

- 目次にC++ちゃんの項目を追加しました
- 髪に付いている髪飾りは今まで「髪留め」と表記していましたが、前者の方がより適切だと思ったので修正しました
- Boostロゴについても追記しました

> C++のGCについてですが、それはReadme.mdではなく個別記事についての追記でしょうか？

混乱させてしまってすみません。GCについては、Readme.mdではなく、もし加えるなら個別記事(第7回)です。
追記するかどうかはお任せいたしますので、issueそのものはcloseいたします。
